# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-01 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('emp_first_name', models.CharField(max_length=50)),
                ('emp_last_name', models.CharField(max_length=50)),
                ('emp_mobile_number', models.BigIntegerField()),
                ('emp_email_id', models.EmailField(max_length=10)),
                ('emp_salary', models.IntegerField()),
                ('emp_location', models.CharField(max_length=100)),
                ('emp_position', models.CharField(max_length=100)),
            ],
        ),
    ]
