# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-01 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudopapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empdata',
            name='emp_email_id',
        ),
        migrations.AddField(
            model_name='empdata',
            name='email_id',
            field=models.EmailField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
