# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-01 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudopapp', '0002_auto_20190401_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empdata',
            old_name='email_id',
            new_name='emp_email_id',
        ),
    ]
